# Generated by Django 6.0 on 2025-12-22 06:50

import apps.users.models
import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "advertisements",
            "0002_carad_brand_carad_color_carad_features_carad_is_new_and_more",
        ),
        ("contenttypes", "0002_remove_content_type_name"),
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelManagers(
            name="user",
            managers=[
                ("objects", apps.users.models.UserManager()),
            ],
        ),
        migrations.RemoveField(
            model_name="dealer",
            name="created_at",
        ),
        migrations.RemoveField(
            model_name="dealer",
            name="updated_at",
        ),
        migrations.RemoveField(
            model_name="user",
            name="created_at",
        ),
        migrations.RemoveField(
            model_name="user",
            name="updated_at",
        ),
        migrations.AddField(
            model_name="user",
            name="about",
            field=models.TextField(blank=True, null=True, verbose_name="О себе"),
        ),
        migrations.AddField(
            model_name="user",
            name="birth_date",
            field=models.DateField(blank=True, null=True, verbose_name="Дата рождения"),
        ),
        migrations.AddField(
            model_name="user",
            name="city",
            field=models.CharField(
                blank=True, max_length=100, null=True, verbose_name="Город"
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="email_verification_sent_at",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Время отправки подтверждения"
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="email_verification_token",
            field=models.CharField(
                blank=True,
                max_length=64,
                null=True,
                verbose_name="Токен подтверждения email",
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="is_email_verified",
            field=models.BooleanField(default=False, verbose_name="Email подтвержден"),
        ),
        migrations.AddField(
            model_name="user",
            name="last_activity",
            field=models.DateTimeField(
                auto_now=True, verbose_name="Последняя активность"
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="receive_email_notifications",
            field=models.BooleanField(
                default=True, verbose_name="Получать email-уведомления"
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="receive_sms_notifications",
            field=models.BooleanField(
                default=False, verbose_name="Получать SMS-уведомления"
            ),
        ),
        migrations.AlterField(
            model_name="dealerreview",
            name="dealer",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="user_dealer_reviews",
                to="users.dealer",
                verbose_name="Дилер",
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="avatar",
            field=models.ImageField(
                blank=True,
                default="avatars/default.jpg",
                null=True,
                upload_to="avatars/%Y/%m/%d/",
                verbose_name="Аватар",
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="email",
            field=models.EmailField(max_length=254, unique=True, verbose_name="Email"),
        ),
        migrations.AlterField(
            model_name="user",
            name="phone",
            field=models.CharField(
                blank=True,
                max_length=20,
                null=True,
                validators=[
                    django.core.validators.RegexValidator(
                        message="Введите номер в формате +7XXXXXXXXXX",
                        regex="^\\+7\\d{10}$",
                    )
                ],
                verbose_name="Телефон",
            ),
        ),
        migrations.CreateModel(
            name="Notification",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "notification_type",
                    models.CharField(
                        choices=[
                            ("message", "Новое сообщение"),
                            ("ad_published", "Объявление опубликовано"),
                            ("ad_rejected", "Объявление отклонено"),
                            ("ad_expired", "Объявление истекло"),
                            ("favorite", "Добавление в избранное"),
                            ("review", "Новый отзыв"),
                            ("system", "Системное уведомление"),
                        ],
                        max_length=20,
                        verbose_name="Тип уведомления",
                    ),
                ),
                ("title", models.CharField(max_length=200, verbose_name="Заголовок")),
                ("message", models.TextField(verbose_name="Сообщение")),
                (
                    "is_read",
                    models.BooleanField(default=False, verbose_name="Прочитано"),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Дата создания"
                    ),
                ),
                ("object_id", models.PositiveIntegerField(blank=True, null=True)),
                (
                    "content_type",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="contenttypes.contenttype",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notifications",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Пользователь",
                    ),
                ),
            ],
            options={
                "verbose_name": "Уведомление",
                "verbose_name_plural": "Уведомления",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="UserActivity",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "activity_type",
                    models.CharField(max_length=50, verbose_name="Тип активности"),
                ),
                (
                    "ip_address",
                    models.GenericIPAddressField(
                        blank=True, null=True, verbose_name="IP адрес"
                    ),
                ),
                (
                    "user_agent",
                    models.TextField(blank=True, null=True, verbose_name="User Agent"),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Время активности"
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="profile_activities",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Пользователь",
                    ),
                ),
            ],
            options={
                "verbose_name": "Активность пользователя",
                "verbose_name_plural": "Активности пользователей",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="UserSettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "show_email",
                    models.BooleanField(default=False, verbose_name="Показывать email"),
                ),
                (
                    "show_phone",
                    models.BooleanField(
                        default=True, verbose_name="Показывать телефон"
                    ),
                ),
                (
                    "show_last_seen",
                    models.BooleanField(
                        default=True,
                        verbose_name="Показывать время последнего посещения",
                    ),
                ),
                (
                    "language",
                    models.CharField(
                        choices=[("ru", "Русский"), ("en", "English")],
                        default="ru",
                        max_length=10,
                        verbose_name="Язык",
                    ),
                ),
                (
                    "timezone",
                    models.CharField(
                        default="Europe/Moscow",
                        max_length=50,
                        verbose_name="Часовой пояс",
                    ),
                ),
                (
                    "theme",
                    models.CharField(
                        choices=[
                            ("light", "Светлая"),
                            ("dark", "Темная"),
                            ("auto", "Авто"),
                        ],
                        default="auto",
                        max_length=20,
                        verbose_name="Тема",
                    ),
                ),
                (
                    "items_per_page",
                    models.IntegerField(
                        default=20, verbose_name="Элементов на странице"
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="settings",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Пользователь",
                    ),
                ),
            ],
            options={
                "verbose_name": "Настройки пользователя",
                "verbose_name_plural": "Настройки пользователей",
            },
        ),
        migrations.CreateModel(
            name="Message",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "text",
                    models.TextField(max_length=2000, verbose_name="Текст сообщения"),
                ),
                (
                    "is_read",
                    models.BooleanField(default=False, verbose_name="Прочитано"),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Дата отправки"
                    ),
                ),
                (
                    "ad",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="messages",
                        to="advertisements.carad",
                        verbose_name="Объявление",
                    ),
                ),
                (
                    "recipient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="profile_messages_received",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Получатель",
                    ),
                ),
                (
                    "sender",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="profile_messages_sent",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Отправитель",
                    ),
                ),
            ],
            options={
                "verbose_name": "Сообщение",
                "verbose_name_plural": "Сообщения",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["sender", "recipient", "created_at"],
                        name="users_messa_sender__194d33_idx",
                    ),
                    models.Index(
                        fields=["is_read"], name="users_messa_is_read_0a8982_idx"
                    ),
                ],
            },
        ),
    ]
