# Generated by Django 6.0 on 2025-12-24 12:59

import apps.advertisements.models
import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name="CarAdFeature",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Создано"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Обновлено"),
                ),
                (
                    "value",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="Значение"
                    ),
                ),
            ],
            options={
                "verbose_name": "Характеристика объявления",
                "verbose_name_plural": "Характеристики объявлений",
                "db_table": "car_ad_features",
            },
        ),
        migrations.CreateModel(
            name="CarPhoto",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Создано"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Обновлено"),
                ),
                (
                    "image",
                    models.ImageField(
                        upload_to=apps.advertisements.models.car_photo_path,
                        verbose_name="Изображение",
                    ),
                ),
                (
                    "thumbnail",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to=apps.advertisements.models.car_photo_path,
                        verbose_name="Миниатюра",
                    ),
                ),
                (
                    "is_main",
                    models.BooleanField(default=False, verbose_name="Главное фото"),
                ),
                ("position", models.IntegerField(default=0, verbose_name="Позиция")),
                (
                    "alt_text",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="Alt текст"
                    ),
                ),
            ],
            options={
                "verbose_name": "Фотография автомобиля",
                "verbose_name_plural": "Фотографии автомобилей",
                "db_table": "car_photos",
                "ordering": ["position"],
            },
        ),
        migrations.CreateModel(
            name="CarView",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Создано"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Обновлено"),
                ),
                (
                    "ip_address",
                    models.GenericIPAddressField(
                        blank=True, null=True, verbose_name="IP адрес"
                    ),
                ),
                ("user_agent", models.TextField(blank=True, verbose_name="User Agent")),
                (
                    "viewed_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Время просмотра"
                    ),
                ),
            ],
            options={
                "verbose_name": "Просмотр",
                "verbose_name_plural": "Просмотры",
                "db_table": "car_views",
                "ordering": ["-viewed_at"],
            },
        ),
        migrations.CreateModel(
            name="City",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Создано"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Обновлено"),
                ),
                (
                    "name",
                    models.CharField(max_length=100, verbose_name="Название города"),
                ),
                (
                    "slug",
                    models.SlugField(max_length=120, unique=True, verbose_name="Slug"),
                ),
                (
                    "region",
                    models.CharField(max_length=100, verbose_name="Регион/Область"),
                ),
                (
                    "country",
                    models.CharField(
                        default="Россия", max_length=100, verbose_name="Страна"
                    ),
                ),
                (
                    "latitude",
                    models.DecimalField(
                        blank=True,
                        decimal_places=6,
                        max_digits=9,
                        null=True,
                        verbose_name="Широта",
                    ),
                ),
                (
                    "longitude",
                    models.DecimalField(
                        blank=True,
                        decimal_places=6,
                        max_digits=9,
                        null=True,
                        verbose_name="Долгота",
                    ),
                ),
                (
                    "population",
                    models.IntegerField(
                        blank=True, null=True, verbose_name="Население"
                    ),
                ),
                (
                    "is_capital",
                    models.BooleanField(default=False, verbose_name="Столица региона"),
                ),
                (
                    "is_major_city",
                    models.BooleanField(default=False, verbose_name="Крупный город"),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="Активен"),
                ),
                (
                    "ads_count",
                    models.IntegerField(
                        default=0, verbose_name="Количество объявлений"
                    ),
                ),
            ],
            options={
                "verbose_name": "Город",
                "verbose_name_plural": "Города",
                "db_table": "cities",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="FavoriteAd",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Создано"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Обновлено"),
                ),
            ],
            options={
                "verbose_name": "Избранное",
                "verbose_name_plural": "Избранные",
                "db_table": "favorite_ads",
            },
        ),
        migrations.CreateModel(
            name="SearchHistory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Создано"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Обновлено"),
                ),
                (
                    "search_query",
                    models.TextField(blank=True, verbose_name="Поисковый запрос"),
                ),
                (
                    "filters",
                    models.JSONField(blank=True, default=dict, verbose_name="Фильтры"),
                ),
                (
                    "results_count",
                    models.IntegerField(
                        blank=True, null=True, verbose_name="Количество результатов"
                    ),
                ),
            ],
            options={
                "verbose_name": "История поиска",
                "verbose_name_plural": "История поиска",
                "db_table": "search_history",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="CarAd",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Создано"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Обновлено"),
                ),
                ("title", models.CharField(max_length=200, verbose_name="Заголовок")),
                (
                    "slug",
                    models.SlugField(
                        blank=True, max_length=220, unique=True, verbose_name="Slug"
                    ),
                ),
                ("description", models.TextField(verbose_name="Описание")),
                (
                    "price",
                    models.DecimalField(
                        decimal_places=2, max_digits=12, verbose_name="Цена"
                    ),
                ),
                (
                    "price_currency",
                    models.CharField(
                        choices=[
                            ("RUB", "₽ Рубль"),
                            ("USD", "$ Доллар"),
                            ("EUR", "€ Евро"),
                            ("KZT", "₸ Тенге"),
                        ],
                        default="RUB",
                        max_length=3,
                        verbose_name="Валюта",
                    ),
                ),
                (
                    "is_negotiable",
                    models.BooleanField(default=False, verbose_name="Торг"),
                ),
                (
                    "year",
                    models.IntegerField(
                        validators=[
                            django.core.validators.MinValueValidator(1900),
                            django.core.validators.MaxValueValidator(
                                apps.advertisements.models.current_year_plus_one
                            ),
                        ],
                        verbose_name="Год выпуска",
                    ),
                ),
                (
                    "vin",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        max_length=17,
                        null=True,
                        unique=True,
                        verbose_name="VIN",
                    ),
                ),
                (
                    "mileage",
                    models.IntegerField(
                        default=0,
                        validators=[django.core.validators.MinValueValidator(0)],
                        verbose_name="Пробег",
                    ),
                ),
                (
                    "mileage_unit",
                    models.CharField(
                        choices=[("км", "Километры"), ("mi", "Мили")],
                        default="км",
                        max_length=10,
                        verbose_name="Единица пробега",
                    ),
                ),
                (
                    "engine_volume",
                    models.DecimalField(
                        blank=True,
                        decimal_places=1,
                        max_digits=3,
                        null=True,
                        verbose_name="Объем двигателя",
                    ),
                ),
                (
                    "engine_power",
                    models.IntegerField(
                        blank=True, null=True, verbose_name="Мощность (л.с.)"
                    ),
                ),
                (
                    "fuel_type",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("petrol", "Бензин"),
                            ("diesel", "Дизель"),
                            ("electric", "Электро"),
                            ("hybrid", "Гибрид"),
                            ("gas", "Газ"),
                            ("petrol_gas", "Бензин+Газ"),
                        ],
                        max_length=20,
                        verbose_name="Топливо",
                    ),
                ),
                (
                    "transmission_type",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("manual", "Механика"),
                            ("automatic", "Автомат"),
                            ("robot", "Робот"),
                            ("variator", "Вариатор"),
                        ],
                        max_length=20,
                        verbose_name="Коробка передач",
                    ),
                ),
                (
                    "drive_type",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("front", "Передний"),
                            ("rear", "Задний"),
                            ("full", "Полный"),
                            ("all_wheel", "Полный (AWD)"),
                            ("four_wheel", "4WD"),
                        ],
                        max_length=20,
                        verbose_name="Привод",
                    ),
                ),
                (
                    "condition",
                    models.CharField(
                        choices=[
                            ("new", "Новый"),
                            ("used", "С пробегом"),
                            ("salvage", "Аварийный"),
                            ("spare_parts", "На запчасти"),
                        ],
                        default="used",
                        max_length=20,
                        verbose_name="Состояние",
                    ),
                ),
                (
                    "color_exterior",
                    models.CharField(
                        blank=True, max_length=50, verbose_name="Цвет кузова"
                    ),
                ),
                (
                    "color_interior",
                    models.CharField(
                        blank=True, max_length=50, verbose_name="Цвет салона"
                    ),
                ),
                (
                    "color",
                    models.CharField(
                        blank=True,
                        help_text="Основной цвет автомобиля",
                        max_length=50,
                        verbose_name="Цвет (общий)",
                    ),
                ),
                (
                    "owner_type",
                    models.CharField(
                        choices=[("private", "Частное лицо"), ("dealer", "Дилер")],
                        default="private",
                        max_length=10,
                        verbose_name="Тип владельца",
                    ),
                ),
                ("region", models.CharField(max_length=100, verbose_name="Регион")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Черновик"),
                            ("active", "Активно"),
                            ("sold", "Продано"),
                            ("expired", "Истекло"),
                            ("banned", "Заблокировано"),
                            ("published", "Опубликовано"),
                            ("pending", "На модерации"),
                        ],
                        default="draft",
                        max_length=20,
                        verbose_name="Статус",
                    ),
                ),
                ("views", models.IntegerField(default=0, verbose_name="Просмотры")),
                (
                    "views_count",
                    models.IntegerField(default=0, verbose_name="Просмотры (count)"),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="Активно"),
                ),
                ("is_new", models.BooleanField(default=True, verbose_name="Новое")),
                (
                    "moderated_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Время модерации"
                    ),
                ),
                (
                    "seats",
                    models.PositiveSmallIntegerField(
                        blank=True,
                        choices=[
                            (2, "2"),
                            (3, "3"),
                            (4, "4"),
                            (5, "5"),
                            (6, "6"),
                            (7, "7"),
                            (8, "8"),
                        ],
                        null=True,
                        verbose_name="Количество мест",
                    ),
                ),
                (
                    "doors",
                    models.PositiveSmallIntegerField(
                        blank=True,
                        choices=[(2, "2"), (3, "3"), (4, "4"), (5, "5")],
                        null=True,
                        verbose_name="Количество дверей",
                    ),
                ),
                (
                    "steering_wheel",
                    models.CharField(
                        choices=[("left", "Левый"), ("right", "Правый")],
                        default="left",
                        max_length=10,
                        verbose_name="Расположение руля",
                    ),
                ),
                (
                    "has_tuning",
                    models.BooleanField(default=False, verbose_name="Есть тюнинг"),
                ),
                (
                    "service_history",
                    models.BooleanField(
                        default=False, verbose_name="Есть сервисная история"
                    ),
                ),
                (
                    "brand",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="ads_direct",
                        to="catalog.carbrand",
                        verbose_name="Марка",
                    ),
                ),
                (
                    "model",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="advertisements",
                        to="catalog.carmodel",
                        verbose_name="Модель",
                    ),
                ),
            ],
            options={
                "verbose_name": "Объявление",
                "verbose_name_plural": "Объявления",
                "db_table": "car_ads",
                "ordering": ["-created_at"],
            },
        ),
    ]
