# Generated by Django 6.0 on 2025-12-19 04:29

import apps.advertisements.models
import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("catalog", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="CarAd",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Создано"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Обновлено"),
                ),
                ("title", models.CharField(max_length=200, verbose_name="Заголовок")),
                (
                    "slug",
                    models.SlugField(max_length=220, unique=True, verbose_name="Slug"),
                ),
                ("description", models.TextField(verbose_name="Описание")),
                (
                    "price",
                    models.DecimalField(
                        decimal_places=2, max_digits=12, verbose_name="Цена"
                    ),
                ),
                (
                    "price_currency",
                    models.CharField(
                        choices=[
                            ("RUB", "₽ Рубль"),
                            ("USD", "$ Доллар"),
                            ("EUR", "€ Евро"),
                            ("KZT", "₸ Тенге"),
                        ],
                        default="RUB",
                        max_length=3,
                        verbose_name="Валюта",
                    ),
                ),
                (
                    "is_negotiable",
                    models.BooleanField(default=False, verbose_name="Торг"),
                ),
                (
                    "year",
                    models.IntegerField(
                        validators=[
                            django.core.validators.MinValueValidator(1900),
                            django.core.validators.MaxValueValidator(
                                apps.advertisements.models.current_year_plus_one
                            ),
                        ],
                        verbose_name="Год выпуска",
                    ),
                ),
                (
                    "vin",
                    models.CharField(
                        blank=True,
                        max_length=17,
                        null=True,
                        unique=True,
                        verbose_name="VIN",
                    ),
                ),
                (
                    "mileage",
                    models.IntegerField(
                        validators=[django.core.validators.MinValueValidator(0)],
                        verbose_name="Пробег",
                    ),
                ),
                (
                    "mileage_unit",
                    models.CharField(
                        default="км", max_length=10, verbose_name="Единица пробега"
                    ),
                ),
                (
                    "engine_volume",
                    models.DecimalField(
                        blank=True,
                        decimal_places=1,
                        max_digits=3,
                        null=True,
                        verbose_name="Объем двигателя",
                    ),
                ),
                (
                    "engine_power",
                    models.IntegerField(
                        blank=True, null=True, verbose_name="Мощность (л.с.)"
                    ),
                ),
                (
                    "fuel_type",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("petrol", "Бензин"),
                            ("diesel", "Дизель"),
                            ("electric", "Электро"),
                            ("hybrid", "Гибрид"),
                            ("gas", "Газ"),
                            ("petrol_gas", "Бензин+Газ"),
                        ],
                        max_length=20,
                        verbose_name="Топливо",
                    ),
                ),
                (
                    "transmission_type",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("manual", "Механика"),
                            ("automatic", "Автомат"),
                            ("robot", "Робот"),
                            ("variator", "Вариатор"),
                        ],
                        max_length=20,
                        verbose_name="Коробка передач",
                    ),
                ),
                (
                    "drive_type",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("front", "Передний"),
                            ("rear", "Задний"),
                            ("full", "Полный"),
                            ("all_wheel", "Полный (AWD)"),
                            ("four_wheel", "4WD"),
                        ],
                        max_length=20,
                        verbose_name="Привод",
                    ),
                ),
                (
                    "condition",
                    models.CharField(
                        choices=[
                            ("new", "Новый"),
                            ("used", "С пробегом"),
                            ("salvage", "Аварийный"),
                            ("spare_parts", "На запчасти"),
                        ],
                        default="used",
                        max_length=20,
                        verbose_name="Состояние",
                    ),
                ),
                (
                    "color_exterior",
                    models.CharField(
                        blank=True, max_length=50, verbose_name="Цвет кузова"
                    ),
                ),
                (
                    "color_interior",
                    models.CharField(
                        blank=True, max_length=50, verbose_name="Цвет салона"
                    ),
                ),
                (
                    "owner_type",
                    models.CharField(
                        choices=[("private", "Частное лицо"), ("dealer", "Дилер")],
                        default="private",
                        max_length=10,
                        verbose_name="Тип владельца",
                    ),
                ),
                ("city", models.CharField(max_length=100, verbose_name="Город")),
                ("region", models.CharField(max_length=100, verbose_name="Регион")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Черновик"),
                            ("active", "Активно"),
                            ("sold", "Продано"),
                            ("expired", "Истекло"),
                            ("banned", "Заблокировано"),
                        ],
                        default="draft",
                        max_length=20,
                        verbose_name="Статус",
                    ),
                ),
                (
                    "views_count",
                    models.IntegerField(default=0, verbose_name="Просмотры"),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="Активно"),
                ),
                (
                    "moderated_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Время модерации"
                    ),
                ),
                (
                    "seats",
                    models.PositiveSmallIntegerField(
                        blank=True, null=True, verbose_name="Количество мест"
                    ),
                ),
                (
                    "doors",
                    models.PositiveSmallIntegerField(
                        blank=True, null=True, verbose_name="Количество дверей"
                    ),
                ),
                (
                    "steering_wheel",
                    models.CharField(
                        choices=[("left", "Левый"), ("right", "Правый")],
                        default="left",
                        max_length=10,
                        verbose_name="Расположение руля",
                    ),
                ),
                (
                    "has_tuning",
                    models.BooleanField(default=False, verbose_name="Есть тюнинг"),
                ),
                (
                    "service_history",
                    models.BooleanField(
                        default=False, verbose_name="Есть сервисная история"
                    ),
                ),
                (
                    "model",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="advertisements",
                        to="catalog.carmodel",
                        verbose_name="Модель",
                    ),
                ),
                (
                    "moderator",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="moderated_ads",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Модератор",
                    ),
                ),
                (
                    "owner",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="advertisements",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Владелец",
                    ),
                ),
            ],
            options={
                "verbose_name": "Объявление",
                "verbose_name_plural": "Объявления",
                "db_table": "car_ads",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="CarView",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Создано"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Обновлено"),
                ),
                (
                    "ip_address",
                    models.GenericIPAddressField(
                        blank=True, null=True, verbose_name="IP адрес"
                    ),
                ),
                ("user_agent", models.TextField(blank=True, verbose_name="User Agent")),
                (
                    "viewed_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Время просмотра"
                    ),
                ),
                (
                    "car_ad",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="views",
                        to="advertisements.carad",
                        verbose_name="Объявление",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="car_views",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Пользователь",
                    ),
                ),
            ],
            options={
                "verbose_name": "Просмотр",
                "verbose_name_plural": "Просмотры",
                "db_table": "car_views",
                "ordering": ["-viewed_at"],
            },
        ),
        migrations.CreateModel(
            name="SearchHistory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Создано"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Обновлено"),
                ),
                (
                    "search_query",
                    models.TextField(blank=True, verbose_name="Поисковый запрос"),
                ),
                (
                    "filters",
                    models.JSONField(blank=True, default=dict, verbose_name="Фильтры"),
                ),
                (
                    "results_count",
                    models.IntegerField(
                        blank=True, null=True, verbose_name="Количество результатов"
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="search_history",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Пользователь",
                    ),
                ),
            ],
            options={
                "verbose_name": "История поиска",
                "verbose_name_plural": "История поиска",
                "db_table": "search_history",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="CarAdFeature",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Создано"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Обновлено"),
                ),
                (
                    "value",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="Значение"
                    ),
                ),
                (
                    "car_ad",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="features",
                        to="advertisements.carad",
                        verbose_name="Объявление",
                    ),
                ),
                (
                    "feature",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="catalog.carfeature",
                        verbose_name="Характеристика",
                    ),
                ),
            ],
            options={
                "verbose_name": "Характеристика объявления",
                "verbose_name_plural": "Характеристики объявлений",
                "db_table": "car_ad_features",
                "unique_together": {("car_ad", "feature")},
            },
        ),
        migrations.CreateModel(
            name="CarPhoto",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Создано"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Обновлено"),
                ),
                (
                    "image",
                    models.ImageField(
                        upload_to=apps.advertisements.models.car_photo_path,
                        verbose_name="Изображение",
                    ),
                ),
                (
                    "thumbnail",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to=apps.advertisements.models.car_photo_path,
                        verbose_name="Миниатюра",
                    ),
                ),
                (
                    "is_main",
                    models.BooleanField(default=False, verbose_name="Главное фото"),
                ),
                ("position", models.IntegerField(default=0, verbose_name="Позиция")),
                (
                    "alt_text",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="Alt текст"
                    ),
                ),
                (
                    "car_ad",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="photos",
                        to="advertisements.carad",
                        verbose_name="Объявление",
                    ),
                ),
            ],
            options={
                "verbose_name": "Фотография автомобиля",
                "verbose_name_plural": "Фотографии автомобилей",
                "db_table": "car_photos",
                "ordering": ["position"],
                "constraints": [
                    models.UniqueConstraint(
                        condition=models.Q(("is_main", True)),
                        fields=("car_ad", "is_main"),
                        name="one_main_photo_per_car",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="FavoriteAd",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Создано"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Обновлено"),
                ),
                (
                    "car_ad",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="advertisements.carad",
                        verbose_name="Объявление",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="favorites",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Пользователь",
                    ),
                ),
            ],
            options={
                "verbose_name": "Избранное",
                "verbose_name_plural": "Избранные",
                "db_table": "favorite_ads",
                "unique_together": {("user", "car_ad")},
            },
        ),
    ]
