# Generated by Django 6.0 on 2025-12-22 06:50

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("advertisements", "0001_initial"),
        ("catalog", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="carad",
            name="brand",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="ads_direct",
                to="catalog.carbrand",
                verbose_name="Марка",
            ),
        ),
        migrations.AddField(
            model_name="carad",
            name="color",
            field=models.CharField(
                blank=True,
                help_text="Основной цвет автомобиля",
                max_length=50,
                verbose_name="Цвет (общий)",
            ),
        ),
        migrations.AddField(
            model_name="carad",
            name="features",
            field=models.ManyToManyField(
                blank=True,
                related_name="advertisements",
                through="advertisements.CarAdFeature",
                to="catalog.carfeature",
                verbose_name="Характеристики",
            ),
        ),
        migrations.AddField(
            model_name="carad",
            name="is_new",
            field=models.BooleanField(default=True, verbose_name="Новое"),
        ),
        migrations.AddField(
            model_name="carad",
            name="views",
            field=models.IntegerField(default=0, verbose_name="Просмотры"),
        ),
        migrations.AlterField(
            model_name="carad",
            name="doors",
            field=models.PositiveSmallIntegerField(
                blank=True,
                choices=[(2, "2"), (3, "3"), (4, "4"), (5, "5")],
                null=True,
                verbose_name="Количество дверей",
            ),
        ),
        migrations.AlterField(
            model_name="carad",
            name="mileage",
            field=models.IntegerField(
                default=0,
                validators=[django.core.validators.MinValueValidator(0)],
                verbose_name="Пробег",
            ),
        ),
        migrations.AlterField(
            model_name="carad",
            name="mileage_unit",
            field=models.CharField(
                choices=[("км", "Километры"), ("mi", "Мили")],
                default="км",
                max_length=10,
                verbose_name="Единица пробега",
            ),
        ),
        migrations.AlterField(
            model_name="carad",
            name="moderator",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="moderated_ads",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Модератор",
            ),
        ),
        migrations.AlterField(
            model_name="carad",
            name="seats",
            field=models.PositiveSmallIntegerField(
                blank=True,
                choices=[
                    (2, "2"),
                    (3, "3"),
                    (4, "4"),
                    (5, "5"),
                    (6, "6"),
                    (7, "7"),
                    (8, "8"),
                ],
                null=True,
                verbose_name="Количество мест",
            ),
        ),
        migrations.AlterField(
            model_name="carad",
            name="slug",
            field=models.SlugField(
                blank=True, max_length=220, unique=True, verbose_name="Slug"
            ),
        ),
        migrations.AlterField(
            model_name="carad",
            name="status",
            field=models.CharField(
                choices=[
                    ("draft", "Черновик"),
                    ("active", "Активно"),
                    ("sold", "Продано"),
                    ("expired", "Истекло"),
                    ("banned", "Заблокировано"),
                    ("published", "Опубликовано"),
                    ("pending", "На модерации"),
                ],
                default="draft",
                max_length=20,
                verbose_name="Статус",
            ),
        ),
        migrations.AlterField(
            model_name="carad",
            name="views_count",
            field=models.IntegerField(default=0, verbose_name="Просмотры (count)"),
        ),
        migrations.AlterField(
            model_name="carad",
            name="vin",
            field=models.CharField(
                blank=True,
                db_index=True,
                max_length=17,
                null=True,
                unique=True,
                verbose_name="VIN",
            ),
        ),
        migrations.AlterField(
            model_name="caradfeature",
            name="car_ad",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="ad_features",
                to="advertisements.carad",
                verbose_name="Объявление",
            ),
        ),
        migrations.AlterField(
            model_name="carview",
            name="car_ad",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="car_views",
                to="advertisements.carad",
                verbose_name="Объявление",
            ),
        ),
        migrations.AlterField(
            model_name="favoritead",
            name="car_ad",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="favorites_rel",
                to="advertisements.carad",
                verbose_name="Объявление",
            ),
        ),
        migrations.AlterField(
            model_name="favoritead",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="favorite_ads_list",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Пользователь",
            ),
        ),
        migrations.CreateModel(
            name="City",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Создано"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Обновлено"),
                ),
                (
                    "name",
                    models.CharField(max_length=100, verbose_name="Название города"),
                ),
                (
                    "slug",
                    models.SlugField(max_length=120, unique=True, verbose_name="Slug"),
                ),
                (
                    "region",
                    models.CharField(max_length=100, verbose_name="Регион/Область"),
                ),
                (
                    "country",
                    models.CharField(
                        default="Россия", max_length=100, verbose_name="Страна"
                    ),
                ),
                (
                    "latitude",
                    models.DecimalField(
                        blank=True,
                        decimal_places=6,
                        max_digits=9,
                        null=True,
                        verbose_name="Широта",
                    ),
                ),
                (
                    "longitude",
                    models.DecimalField(
                        blank=True,
                        decimal_places=6,
                        max_digits=9,
                        null=True,
                        verbose_name="Долгота",
                    ),
                ),
                (
                    "population",
                    models.IntegerField(
                        blank=True, null=True, verbose_name="Население"
                    ),
                ),
                (
                    "is_capital",
                    models.BooleanField(default=False, verbose_name="Столица региона"),
                ),
                (
                    "is_major_city",
                    models.BooleanField(default=False, verbose_name="Крупный город"),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="Активен"),
                ),
                (
                    "ads_count",
                    models.IntegerField(
                        default=0, verbose_name="Количество объявлений"
                    ),
                ),
            ],
            options={
                "verbose_name": "Город",
                "verbose_name_plural": "Города",
                "db_table": "cities",
                "ordering": ["name"],
                "indexes": [
                    models.Index(
                        fields=["name", "region"], name="cities_name_87a5de_idx"
                    ),
                    models.Index(
                        fields=["is_active"], name="cities_is_acti_a959ab_idx"
                    ),
                    models.Index(fields=["slug"], name="cities_slug_905566_idx"),
                ],
            },
        ),
        migrations.AlterField(
            model_name="carad",
            name="city",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="advertisements",
                to="advertisements.city",
                verbose_name="Город",
            ),
        ),
        migrations.AddIndex(
            model_name="carad",
            index=models.Index(
                fields=["status", "is_active"], name="car_ads_status_d7c5af_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="carad",
            index=models.Index(fields=["price"], name="car_ads_price_62418a_idx"),
        ),
        migrations.AddIndex(
            model_name="carad",
            index=models.Index(
                fields=["created_at"], name="car_ads_created_778c27_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="carad",
            index=models.Index(fields=["slug"], name="car_ads_slug_47020a_idx"),
        ),
    ]
