# Generated by Django 6.0 on 2025-12-22 07:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        (
            "advertisements",
            "0002_carad_brand_carad_color_carad_features_carad_is_new_and_more",
        ),
        ("catalog", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="DailyStats",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Создано"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Обновлено"),
                ),
                ("date", models.DateField(unique=True, verbose_name="Дата")),
                (
                    "new_users",
                    models.IntegerField(default=0, verbose_name="Новые пользователи"),
                ),
                (
                    "active_users",
                    models.IntegerField(
                        default=0, verbose_name="Активные пользователи"
                    ),
                ),
                (
                    "new_ads",
                    models.IntegerField(default=0, verbose_name="Новые объявления"),
                ),
                (
                    "active_ads",
                    models.IntegerField(default=0, verbose_name="Активные объявления"),
                ),
                (
                    "sold_ads",
                    models.IntegerField(default=0, verbose_name="Проданные объявления"),
                ),
                (
                    "total_views",
                    models.IntegerField(default=0, verbose_name="Всего просмотров"),
                ),
                (
                    "unique_views",
                    models.IntegerField(default=0, verbose_name="Уникальные просмотры"),
                ),
                (
                    "searches",
                    models.IntegerField(default=0, verbose_name="Поисковые запросы"),
                ),
                (
                    "popular_searches",
                    models.JSONField(
                        blank=True, default=list, verbose_name="Популярные запросы"
                    ),
                ),
                (
                    "messages_sent",
                    models.IntegerField(default=0, verbose_name="Отправлено сообщений"),
                ),
                (
                    "payments_amount",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=12,
                        verbose_name="Сумма платежей",
                    ),
                ),
                (
                    "payments_count",
                    models.IntegerField(default=0, verbose_name="Количество платежей"),
                ),
                (
                    "conversion_rate",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=5,
                        verbose_name="Конверсия",
                    ),
                ),
            ],
            options={
                "verbose_name": "Ежедневная статистика",
                "verbose_name_plural": "Ежедневная статистика",
            },
        ),
        migrations.CreateModel(
            name="ConversionEvent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Создано"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Обновлено"),
                ),
                (
                    "event_type",
                    models.CharField(
                        choices=[
                            ("view_to_contact", "Просмотр → Контакт"),
                            ("contact_to_deal", "Контакт → Сделка"),
                            ("search_to_view", "Поиск → Просмотр"),
                            ("view_to_favorite", "Просмотр → Избранное"),
                        ],
                        max_length=50,
                        verbose_name="Тип события",
                    ),
                ),
                (
                    "data",
                    models.JSONField(blank=True, default=dict, verbose_name="Данные"),
                ),
                (
                    "session_id",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="ID сессии"
                    ),
                ),
                (
                    "car_ad",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="conversion_events",
                        to="advertisements.carad",
                        verbose_name="Объявление",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="conversion_events",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Пользователь",
                    ),
                ),
            ],
            options={
                "verbose_name": "Событие конверсии",
                "verbose_name_plural": "События конверсии",
                "db_table": "conversion_events",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="PageView",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Создано"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Обновлено"),
                ),
                (
                    "page_url",
                    models.URLField(max_length=500, verbose_name="URL страницы"),
                ),
                (
                    "page_title",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="Заголовок страницы"
                    ),
                ),
                (
                    "referrer",
                    models.URLField(blank=True, max_length=500, verbose_name="Реферер"),
                ),
                (
                    "ip_address",
                    models.GenericIPAddressField(
                        blank=True, null=True, verbose_name="IP адрес"
                    ),
                ),
                ("user_agent", models.TextField(blank=True, verbose_name="User Agent")),
                (
                    "session_id",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="ID сессии"
                    ),
                ),
                (
                    "device_type",
                    models.CharField(
                        blank=True, max_length=50, verbose_name="Тип устройства"
                    ),
                ),
                (
                    "browser",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="Браузер"
                    ),
                ),
                (
                    "os",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="Операционная система"
                    ),
                ),
                (
                    "viewed_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Время просмотра"
                    ),
                ),
                (
                    "time_on_page",
                    models.IntegerField(
                        blank=True, null=True, verbose_name="Время на странице (сек)"
                    ),
                ),
                (
                    "car_ad",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="page_views",
                        to="advertisements.carad",
                        verbose_name="Объявление",
                    ),
                ),
                (
                    "car_brand",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="catalog.carbrand",
                        verbose_name="Марка",
                    ),
                ),
                (
                    "car_model",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="catalog.carmodel",
                        verbose_name="Модель",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="page_views",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Пользователь",
                    ),
                ),
            ],
            options={
                "verbose_name": "Просмотр страницы",
                "verbose_name_plural": "Просмотры страниц",
                "db_table": "page_views",
                "ordering": ["-viewed_at"],
                "indexes": [
                    models.Index(
                        fields=["page_url"], name="page_views_page_ur_a48fb0_idx"
                    ),
                    models.Index(
                        fields=["viewed_at"], name="page_views_viewed__c1e23c_idx"
                    ),
                    models.Index(fields=["user"], name="page_views_user_id_2669f2_idx"),
                ],
            },
        ),
        migrations.CreateModel(
            name="SearchAnalytics",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Создано"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Обновлено"),
                ),
                ("query", models.CharField(max_length=200, verbose_name="Запрос")),
                (
                    "filters",
                    models.JSONField(blank=True, default=dict, verbose_name="Фильтры"),
                ),
                (
                    "results_count",
                    models.IntegerField(
                        blank=True, null=True, verbose_name="Количество результатов"
                    ),
                ),
                (
                    "has_results",
                    models.BooleanField(default=False, verbose_name="Есть результаты"),
                ),
                (
                    "ip_address",
                    models.GenericIPAddressField(
                        blank=True, null=True, verbose_name="IP адрес"
                    ),
                ),
                (
                    "session_id",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="ID сессии"
                    ),
                ),
                (
                    "searched_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Время поиска"
                    ),
                ),
                (
                    "clicked_result",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="search_clicks",
                        to="advertisements.carad",
                        verbose_name="Кликнутое объявление",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="search_analytics",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Пользователь",
                    ),
                ),
            ],
            options={
                "verbose_name": "Аналитика поиска",
                "verbose_name_plural": "Аналитика поиска",
                "db_table": "search_analytics",
                "ordering": ["-searched_at"],
                "indexes": [
                    models.Index(fields=["query"], name="search_anal_query_2ffb31_idx"),
                    models.Index(
                        fields=["searched_at"], name="search_anal_searche_efad9b_idx"
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="UserActivity",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Создано"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Обновлено"),
                ),
                (
                    "activity_type",
                    models.CharField(
                        choices=[
                            ("login", "Вход"),
                            ("logout", "Выход"),
                            ("register", "Регистрация"),
                            ("view_ad", "Просмотр объявления"),
                            ("create_ad", "Создание объявления"),
                            ("edit_ad", "Редактирование объявления"),
                            ("delete_ad", "Удаление объявления"),
                            ("send_message", "Отправка сообщения"),
                            ("add_favorite", "Добавление в избранное"),
                            ("remove_favorite", "Удаление из избранного"),
                            ("search", "Поиск"),
                            ("subscribe", "Подписка"),
                            ("payment", "Оплата"),
                        ],
                        max_length=50,
                        verbose_name="Тип активности",
                    ),
                ),
                (
                    "data",
                    models.JSONField(blank=True, default=dict, verbose_name="Данные"),
                ),
                (
                    "ip_address",
                    models.GenericIPAddressField(
                        blank=True, null=True, verbose_name="IP адрес"
                    ),
                ),
                ("user_agent", models.TextField(blank=True, verbose_name="User Agent")),
                (
                    "car_ad",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="activities",
                        to="advertisements.carad",
                        verbose_name="Объявление",
                    ),
                ),
                (
                    "target_user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="targeted_activities",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Целевой пользователь",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="analytics_activities",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Пользователь",
                    ),
                ),
            ],
            options={
                "verbose_name": "Активность пользователя",
                "verbose_name_plural": "Активность пользователей",
                "db_table": "user_activities",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["user", "activity_type"],
                        name="user_activi_user_id_290628_idx",
                    ),
                    models.Index(
                        fields=["created_at"], name="user_activi_created_9fa3ca_idx"
                    ),
                ],
            },
        ),
    ]
