# Generated by Django 6.0 on 2025-12-19 04:29

import apps.catalog.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="CarBrand",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Создано"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Обновлено"),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=100, unique=True, verbose_name="Название"
                    ),
                ),
                (
                    "slug",
                    models.SlugField(max_length=120, unique=True, verbose_name="Slug"),
                ),
                (
                    "country",
                    models.CharField(default="RU", max_length=2, verbose_name="Страна"),
                ),
                ("description", models.TextField(blank=True, verbose_name="Описание")),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="Активно"),
                ),
                (
                    "logo",
                    models.ImageField(
                        blank=True,
                        help_text="Рекомендуемый размер: 300x300 пикселей",
                        null=True,
                        upload_to=apps.catalog.models.car_brand_logo_path,
                        verbose_name="Логотип",
                    ),
                ),
            ],
            options={
                "verbose_name": "Марка автомобиля",
                "verbose_name_plural": "Марки автомобилей",
                "db_table": "car_brands",
            },
        ),
        migrations.CreateModel(
            name="CarFeature",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Создано"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Обновлено"),
                ),
                ("name", models.CharField(max_length=100, verbose_name="Название")),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("safety", "Безопасность"),
                            ("comfort", "Комфорт"),
                            ("multimedia", "Мультимедиа"),
                            ("exterior", "Экстерьер"),
                            ("interior", "Интерьер"),
                            ("other", "Другое"),
                        ],
                        max_length=50,
                        verbose_name="Категория",
                    ),
                ),
                (
                    "icon",
                    models.CharField(blank=True, max_length=50, verbose_name="Иконка"),
                ),
                (
                    "is_filterable",
                    models.BooleanField(default=False, verbose_name="Для фильтра"),
                ),
                ("position", models.IntegerField(default=0, verbose_name="Позиция")),
            ],
            options={
                "verbose_name": "Характеристика",
                "verbose_name_plural": "Характеристики",
                "db_table": "car_features",
                "ordering": ["category", "position"],
            },
        ),
        migrations.CreateModel(
            name="CarModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Создано"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Обновлено"),
                ),
                (
                    "name",
                    models.CharField(max_length=100, verbose_name="Название модели"),
                ),
                (
                    "slug",
                    models.SlugField(max_length=120, unique=True, verbose_name="Slug"),
                ),
                (
                    "body_type",
                    models.CharField(
                        blank=True, max_length=50, verbose_name="Тип кузова"
                    ),
                ),
                (
                    "year_start",
                    models.IntegerField(
                        blank=True, null=True, verbose_name="Год начала выпуска"
                    ),
                ),
                (
                    "year_end",
                    models.IntegerField(
                        blank=True, null=True, verbose_name="Год окончания выпуска"
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="Активно"),
                ),
                ("description", models.TextField(blank=True, verbose_name="Описание")),
                (
                    "image",
                    models.ImageField(
                        blank=True,
                        help_text="Рекомендуемый размер: 800x600 пикселей",
                        null=True,
                        upload_to=apps.catalog.models.car_model_image_path,
                        verbose_name="Изображение",
                    ),
                ),
                (
                    "brand",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="models",
                        to="catalog.carbrand",
                        verbose_name="Марка",
                    ),
                ),
            ],
            options={
                "verbose_name": "Модель автомобиля",
                "verbose_name_plural": "Модели автомобилей",
                "db_table": "car_models",
            },
        ),
    ]
